sudo: false
os:
  - linux
  - windows
language: go
go:
  - "1.x"
  - "1.9.x"
  - master
matrix:
  allow_failures:
    - go: master
  fast_finish: true
go_import_path: sourcegraph.com/sourcegraph/go-vcs
install:
  - # Do nothing. This is needed to prevent default install action "go get -t -v ./..." from happening here (we want it to happen inside script step).
script:
  - go get -t -v ./...
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go test -v -race ./...
